/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.olc2.gui;

import com.alee.extended.painter.PainterListener;
import com.alee.extended.painter.TexturePainter;
import com.alee.extended.window.ComponentMoveAdapter;
import com.alee.laf.WebLookAndFeel;
import com.alee.laf.panel.WebPanel;
import com.alee.laf.rootpane.WebFrame;
import com.alee.laf.scroll.WebScrollPane;
import com.alee.laf.tabbedpane.TabStretchType;
import com.alee.laf.tabbedpane.TabbedPaneStyle;
import com.alee.laf.tabbedpane.WebTabbedPane;
import com.olc2.cswing.CBrowserPane;
import com.olc2.cswing.CTab;
import com.olc2.cswing.CTabbedPaneUI;
import com.olc2.model.TabList;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JTextArea;

/**
 *
 * @author henry
 */
public class MainFrame extends WebFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        //Personalización
        ComponentMoveAdapter.install(tabPaneNavegador, MainFrame.this);
        this.center();
        this.setIconImages(WebLookAndFeel.getImages());
        this.setInactiveShadeWidth(5);
        this.setShadeWidth(0);
        this.setShowTitleComponent(false);
        this.setWindowOpacity(0.95f);
        //
        
        tabPaneNavegador.setUI(new CTabbedPaneUI());
        JTextArea txtEditor = new JTextArea();
        txtEditor.setEditable(false);
        txtEditor.setColumns(20);
        txtEditor.setRows(5);
        txtEditor.setFocusable(false);
        WebScrollPane scrollEditor = new WebScrollPane(txtEditor);
        tabPaneNavegador.addTab("", scrollEditor);
        tabPaneNavegador.addTab("", new CBrowserPane());
        int i = TabList.getInstancia().getTabID();
        tabPaneNavegador.setTabComponentAt(0, new CTab(tabPaneNavegador, i, "Facebook"));
        TabList.getInstancia().add(new CTab(tabPaneNavegador, i, "Facebook"));
        i = TabList.getInstancia().getTabID();
        tabPaneNavegador.setTabComponentAt(1, new CTab(tabPaneNavegador, i, ""));
        //((WebTabbedPane)tabPaneNavegador).setSelectedTopBg(new Color(23, 32, 42));
        ((WebTabbedPane)tabPaneNavegador).setTabOverlay(1);
        //((WebTabbedPane)tabPaneNavegador).setTabInsets(new Insets(3, 10, 3, 10));
        ((WebTabbedPane)tabPaneNavegador).setTabStretchType(TabStretchType.never);
        //((WebTabbedPane)tabPaneNavegador).setTabbedPaneStyle(TabbedPaneStyle.standalone);
        TabList.getInstancia().add(new CTab(tabPaneNavegador, i, ""));
        ((WebTabbedPane)tabPaneNavegador).setTabbedPaneStyle(TabbedPaneStyle.attached);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPaneNavegador = new WebTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPaneNavegador, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPaneNavegador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WebLookAndFeel.install();
                WebLookAndFeel.setDecorateAllWindows(true);
                WebLookAndFeel.setAllowLinuxTransparency(true);
                WebFrame.setDefaultLookAndFeelDecorated(true);
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabPaneNavegador;
    // End of variables declaration//GEN-END:variables
}
